### ISSUE TITLE
Siri support

### ISSUE THREAD

**Issue by Dynvsty** [SpotCompiled/SpotC-Plus-Plus#1]
Is it possible to get Siri to play from this tweaked Spotify?

**Comment by yodaluca23** [comment]
> Is it possible to get Siri to play from this tweaked Spotify?

It is possible, if you are playing something currently, you can ask Siri to Play/Pause fast forward, etc. However, you are not able to go from not playing anything to asking Siri to play a specific playlist off of Spotify, due to sideloading limitations...
