### ISSUE TITLE
Scarlet doesn’t work

### ISSUE THREAD

**Issue by DrakeNotRapper** [SpotCompiled/SpotC-Plus-Plus#12]
I get the “Integrity could not be verified” text when I downloaded through scarlet, not due to revoked cert as I have other apps installed.

**Comment by skywolfhaley** [comment]
then use sideloadly

**Comment by freakazoiddd** [comment]
i found a work around; after clicking on the IPA you want to side load the normal way (clicking side load and then going to downloads or whatever folder) go to the folder named scarlet in “on my iphone” and click on the “signedipa” ipa, you might have to do it a few times but this is what worked for me when i used to use scarlet (use sidestore)

**Comment by yodaluca23** [comment]
Does this happen with the latest release?

**Comment by Kaspeck** [comment]
Yes, this does happen with the latest release. The workaround for me was sideloading the ipa, as soon as it started i went to the Scarlet folder while in the "Sideload IPA" area. When Scarlet asks u to install the ipa click no and press on signedipa.ipa.

**Comment by yodaluca23** [comment]
The latest release was compiled with Pyzule instead of Sideloadly, is this still happening?

**Comment by yodaluca23** [comment]
> The latest release was compiled with Pyzule instead of Sideloadly, is this still happening?

@Kaspeck @DrakeNotRapper @freakazoiddd ???

**Comment by Kaspeck** [comment]
This worked with Scarlet; I didn't have to use the workaround.
