### ISSUE TITLE
No lyrics view? on iphone 14 plus

### ISSUE THREAD

**Issue by aaronliu0130** [SpotCompiled/SpotC-Plus-Plus#13]
https://github.com/SpotCompiled/SpotC-Plus-Plus/assets/11874211/0e77d4f7-e017-42b2-8f25-e87ffd8713bf

**Comment by yodaluca23** [comment]
Do you have lyric card enabled? Settings > Top right hamburger menu > Realtime Lyric Card & Realtime Lyric Button enabled

**Comment by aaronliu0130** [comment]
Oh yeah that solved it. The “real-time lyrics button” setting doesn’t do anything though
