### ISSUE TITLE
Spotify app does not show in Carplay.

### ISSUE THREAD

**Issue by KojimazenX** [SpotCompiled/SpotC-Plus-Plus#14]
When connected to carplay, the apps does not show.
Going into Settings>general>carplay, there is also no options of adding it into Carplay.
Playing music via SpotC++ during carplay has audio through car speakers but no display for controls on Carplay in the car's headunit

![WhatsApp Image 2023-10-02 at 11 10 18 AM](https://github.com/SpotCompiled/SpotC-Plus-Plus/assets/146690046/0fa8c532-31ae-4ba2-a77d-e1afed51ae48)

**Comment by yodaluca23** [comment]
Pretty sure I stripped the CarPlay stuff, I think it would require additional entitlements anyways, that idk if even a developer certificate has... you could download the AppStore Spotify app and use that while in the car... the CarPlay version wouldn't have any of the tweaks anyways...

**Comment by ceedveed** [comment]
> Pretty sure I stripped the CarPlay stuff, I think it would require additional entitlements anyways, that idk if even a developer certificate has... you could download the AppStore Spotify app and use that while in the car... the CarPlay version wouldn't have any of the tweaks anyways...

Is there anyway you can add a version that keeps the CarPlay entitlements? They work with CarPlay if installed with TrollStore.
