### ISSUE TITLE
Update to the latest Spotify version?

### ISSUE THREAD

**Issue by SirDank** [SpotCompiled/SpotC-Plus-Plus#16]
I've been following this for quite a while, expecting an update. It's been 10 months since the last release, will this be updated soon?

**Comment by yodaluca23** [comment]
It will not be updated to any later Spotify version unless Julioverne updates Spotilife to support higher versions... Though I am trying to fix a couple of the issues with some of the tweaks, and will release a new version on the same Spotify version once I'm done...

**Comment by yodaluca23** [comment]
By the way, don't know if you noticed, or are subscribed for notifications for new releases, but I've switched over to EeveeSpotify replacing Spotilife, using the latest version! @SirDank

**Comment by SirDank** [comment]
@yodaluca23 I've done the same!

**Comment by yodaluca23** [comment]
> @yodaluca23 I've done the same!

I mean that the latest release includes EeeveeSpotify, so you can use the latest release here 
https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/latest
That uses the latest Spotify version.

**Comment by SirDank** [comment]
> > @yodaluca23 I've done the same!
> 
> I mean that the latest release includes EeeveeSpotify, so you can use the latest release here https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/latest That uses the latest Spotify version.

oh wait so how is SpotC++ different from just EeveeSpotify?

**Comment by yodaluca23** [comment]
> oh wait so how is SpotC++ different from just EeveeSpotify?

It also has Sposify, and more tweaks coming
