### ISSUE TITLE
The app frequently logs me out and reverts to an unmodded Spotify app

### ISSUE THREAD

**Issue by JayceTheBased** [SpotCompiled/SpotC-Plus-Plus#17]
Let me start off by saying thank you so much for this app. I really appreciate your work on this, especially the Sposify integration that allows me to stop that terrible forced shuffle on playlists.

The problem I'm having is that the app frequently logs me out and reverts back to an unmodded Spotify app if I log back in. I don't know how that's possible, but it happens every other time I refresh the app, exactly 4 days after I refresh it. 

Sideload tool used: sideloadly
Phone model: iPhone 7
iOS version: 15.8.
Ipa Version: SpotC++ v1.1.3

**Comment by jayden0922** [comment]
I have same problem. Did u solve this problem?

**Comment by crumhirnd** [comment]
I just noticed, today I was out and the app logged me out. When I logged back in the app was back to stock. When I returned home (connected to WiFi) the tweaks came back..

**Comment by jayden0922** [comment]
> I just noticed, today I was out and the app logged me out. When I logged back in the app was back to stock. When I returned home (connected to WiFi) the tweaks came back..

How did that happen?

**Comment by JayceTheBased** [comment]
> > I just noticed, today I was out and the app logged me out. When I logged back in the app was back to stock. When I returned home (connected to WiFi) the tweaks came back..

Thanks for your response and sorry for my slow response. I tried waiting for several hours and found out that it does indeed start working again on its own. In my experience, it doesn't seem to be anything specifically related to what network you're connected to as I noticed that it stopped and then started working while I was connected to my home WiFi over a 4-6 hour period.

> I have same problem. Did u solve this problem?

To avoid having to wait, I switched to using sidestore, which is pretty awesome. Just make sure you only set it up with an apple id that's already been signed into your iPhone. With sidestore I can refresh the app on demand untethered and it also autorefreshes the app every few days so I rarely get this problem anymore. If I do encounter it, I just refresh the app manually. I would consider that to be an easy and satisfactory solution so you can close this issue if you want @yodaluca23.

**Comment by yodaluca23** [comment]
EeveeSpotify adds a notification when Spotify refreshes user data, this will tell prompt you to force close, and clear user data if issue presists.
