### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Fa2sa1** [SpotCompiled/SpotC-Plus-Plus#18]
I can put me acc on it for some reason

**Comment by XaviXE** [comment]
I think you cannot login with google, facebook, apple and that stuff. Is that your problem?

**Comment by carrotfarmer** [comment]
Try logging in with your email and password. OAuth didn't work for me, but email/password did

**Comment by yodaluca23** [comment]
OAuth needs special entitlements you probably don't have, should work with troll store though...
