### ISSUE TITLE
Are there going to be more updates?

### ISSUE THREAD

**Issue by XaviXE** [SpotCompiled/SpotC-Plus-Plus#19]
It's been over a year since the last release and I was wondering if you are planning to update the app to the latest version of Spotify at some point. I really appreciate your work :D

**Comment by yodaluca23** [comment]
The latest version of Spotify, is not compatible with Spotilife, as soon as Julioverne, has an update to Spotilife, then I will...

**Comment by XaviXE** [comment]
Now I'm using Spotify Deluxe from appdb.to
It also use Spotlife and is on the latest version ¯\_(ツ)_/¯

**Comment by XaviXE** [comment]
So after some research I fond that the last version of Spotify Deluxe has problems. Was nice at first :)

**Comment by yodaluca23** [comment]
By the way, don't know if you noticed, or are subscribed for notifications for new releases, but I've switched over to EeveeSpotify replacing Spotilife, using the latest version!

**Comment by XaviXE** [comment]
Thank you! I didn't get the notification (turns out I didn't follow the repo 😅). I'll try the new version :)
