### ISSUE TITLE
Crashes when seeking to specific lyric

### ISSUE THREAD

**Issue by ttuleyb** [SpotCompiled/SpotC-Plus-Plus#2]
Go to any song, expand the lyrics and click on any text, the app crashes.

**Comment by Spritzerland** [comment]
This also happens to me

**Comment by bachig26** [comment]
@yodaluca23 Me too...

### Clip

https://user-images.githubusercontent.com/96393348/227842525-df726881-1a52-4b52-867b-e13a97c3b87d.MOV

**Comment by yodaluca23** [comment]
I'm currently working on implementing a fix (Thanks to [level3tjg](https://github.com/level3tjg)) that should be out in the next update.

**Comment by Dynvsty** [comment]
> I'm currently working on implementing a fix (Thanks to [level3tjg](https://github.com/level3tjg)) that should be out in the next update.

Any update? sorry to bother you

**Comment by yodaluca23** [comment]
EeveeSpotify introduces a new lyric system, I have tested this and the bug no longer seems present, closing.
