### ISSUE TITLE
RTL is bugged

### ISSUE THREAD

**Issue by freakazoiddd** [SpotCompiled/SpotC-Plus-Plus#20]
songs that have real time lyrics on the normal spotify app/musixmatch just have a chance of not showing up or showing up as “could not load lyrics” no matter what i do.

**Comment by yodaluca23** [comment]
Do you have Sposify's show lyrics on?

**Comment by freakazoiddd** [comment]
> Do you have Sposify's show lyrics on?

yup, all custom options about lyrics are turned on as well, i forgot to mention i also get this bug with canvas (songs may not have canvas or lyrics, just canvas, or just lyrics) this happens on songs that work fine on my brothers spotify who actually has premium and such.

**Comment by yodaluca23** [comment]
EeveeSpotify introduces a new lyrics system.
