### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by Kaspeck** [SpotCompiled/SpotC-Plus-Plus#24]
When I play music and turn off my phone screen the music stops playing after a couple seconds. When I reopen the minimized app I cannot play any music and have to restart the app.

**Comment by Kaspeck** [comment]
Doesn't work, the other issue on Eevie's spotify also said it doesn't work.

**Comment by Sananjavaidkhan** [comment]
**[Download spotify ++ for pc](https://spotypre.com/spotify-plus/)**

**Comment by Kaspeck** [comment]
U can close this issue, it began working a week after starting this issue.
