### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by TheMage217** [SpotCompiled/SpotC-Plus-Plus#25]
On latest IOS update, settings available after hitting the three bars/burger menu icon are not working. "Disable Add Song Button" is not working, even after restarting the app and "Blackout mode" seemingly does not do anything.

**Comment by yodaluca23** [comment]
Lots of the Sposify settings, are likely not compatible with the latest version of Spotify, nothing I can do unless aesthyrica releases an update...
