### ISSUE TITLE
Spotc++ not updating on sidestore

### ISSUE THREAD

**Issue by Ale-su** [SpotCompiled/SpotC-Plus-Plus#26]
Like the title says i tried both spotveec and spotc++ and they re both stuck on older version, idk if its a problem with sidestore.

![image](https://github.com/SpotCompiled/SpotC-Plus-Plus/assets/76785050/28d93e79-fbc5-4171-8809-6fe3f1b53b8d)
![image](https://github.com/SpotCompiled/SpotC-Plus-Plus/assets/76785050/f4b17425-2de0-4b05-86d0-b9b6b7c4b92b)

**Comment by Ale-su** [comment]
nvm fixed by removing the repo and re adding it again

**Comment by yodaluca23** [comment]
Well, I was going to say that ether something wrong with your environment, or you're using a different source.
