### ISSUE TITLE
Bundle ID mismatch not letting me install

### ISSUE THREAD

**Issue by lor1x** [SpotCompiled/SpotC-Plus-Plus#27]
Hi,

After removing and adding the source (as it was not picking up the latest version) and trying to do a fresh install it is stopping halfway through complaining about the bundle ID.

This is the error SideStore is throwing:
"Spotify" could not be installed.
The bundle ID "com.spotify.client" does not match the one specified by the source ("com.yodaluca23.SpotCPlusPlus").

**Comment by p-sage** [comment]
I have the exact same problem...

**Comment by yodaluca23** [comment]
Dang it, I was hoping this wouldn’t happen. I will have to fix it and re-upload it. I rushed the last release.

**Comment by Ale-su** [comment]
had the sane problem fixed it by changing the ipa bundle id with sideloadly and extracting the ipa

**Comment by yodaluca23** [comment]
Ok guys, I reuploaded the .ipa, can yall try it again now?

**Comment by lor1x** [comment]
It works now. Thank you!
