### ISSUE TITLE
OpenSpotifySafariExtension not appearing

### ISSUE THREAD

**Issue by Blahx** [SpotCompiled/SpotC-Plus-Plus#28]
I read that you included the extension in the ipa, however I am unable to find the extension in safari, after installing the ipa via Trollstore

**Comment by yodaluca23** [comment]
Yes, I recently added it, are you on the latest release? Make sure you enable it in safari and give it permission to access websites.

**Comment by Blahx** [comment]
Yes I am on 2.1.0

I do not see it on the list of extensions.

**Comment by yodaluca23** [comment]
> Yes I am on 2.1.0
> 
> I do not see it on the list of extensions.

Try the latest release?

Settings > Safari > Extensions

You don't see Open In Spotify?

**Comment by yodaluca23** [comment]
What iOS version are you on?

**Comment by yodaluca23** [comment]
Also, are you stripping the app extensions for some reason?

**Comment by yodaluca23** [comment]
> Ok, in my usual habit I had deleted the extension, I will download it again next week ![image](https://private-user-images.githubusercontent.com/164814887/342905519-6523af8d-c6a4-45cd-a42d-aaceb7e7df2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDU0NzcsIm5iZiI6MTcxOTM0NTE3NywicGF0aCI6Ii8xNjQ4MTQ4ODcvMzQyOTA1NTE5LTY1MjNhZjhkLWM2YTQtNDVjZC1hNDJkLWFhY2ViN2U3ZGYyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxOTUyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Mzg4YWM2YjQ4Zjc0NGY5NzdkY2EwZmY4N2MzMzE2MTQ2OGVkYmI3ZGFjYzZmNzNmZmE1ZDMyNThlMjQ5NGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8xp6H8VRigGKJcnb6EYjPmKYX9G4t9SHrCDMcJVKwpM)

That would be your probablem, the safari extension is an extension.. lol. Don't know why I didn't think this first...

**Comment by yodaluca23** [comment]
@Blahx Any updates? Did that work?

**Comment by yodaluca23** [comment]
What iOS version are you on?
I believe most virgins that support troll store have a jailbreak available now if you can, then I would just install the following tweaks (these are what is bundled):

[EeveeSpotify](https://github.com/whoeevee/EeveeSpotify)
[SwiftProtobuf](https://github.com/whoeevee/EeveeSpotify)
[Orion](https://chariz.com/get/orion-runtime14)
[Sposify](https://www.ios-repo-updates.com/repository/dynastic/package/com.spos)
[SposifyFix](https://www.ios-repo-updates.com/repository/level3tjg/package/com.level3tjg.sposifyfix)
