### ISSUE TITLE
Clicking music player doesn’t open Spotify

### ISSUE THREAD

**Issue by calvincorrieri** [SpotCompiled/SpotC-Plus-Plus#32]
Title says it all. If I click on the dynamic island, control center player, or lock screen player, Spotify doesn’t open. It works with sideloaded YouTube so idk what the problem is.

**Comment by yodaluca23** [comment]
> Title says it all. If I click on the dynamic island, control center player, or lock screen player, Spotify doesn’t open. It works with sideloaded YouTube so idk what the problem is.

Works for me... What signing tool are you using?

**Comment by calvincorrieri** [comment]
AppDB with my own dev certificate. Do I need to enable certain options when signing or something?
