### ISSUE TITLE
Request: Tweak to enable A/B flag selection

### ISSUE THREAD

**Issue by correii** [SpotCompiled/SpotC-Plus-Plus#33]
Idk if this would be possible with Spotify, like if it’s a server side thing or not. But there’s a tweak for YouTube that lets you play around with the A/B flags. It would be cool to do that with Spotify too.

If this is the wrong place to request this, please tell me where I should go instead.

**Comment by yodaluca23** [comment]
https://github.com/whoeevee/EeveeSpotify/issues/240

**Comment by yodaluca23** [comment]
Closing this for now, if I ever get more time on my plate I might come back to this, but right now, this isn't a priority.

**Comment by correii** [comment]
> Closing this for now, if I ever get more time on my plate I might come back to this, but right now, this isn't a priority.

Word. I appreciate you giving it some thought.
