### ISSUE TITLE
failed at GitHub Release

### ISSUE THREAD

**Issue by bachig26** [SpotCompiled/SpotC-Plus-Plus#34]
@yodaluca23 
Hi, I tried the new workflow for building ipa with the tweak.
can you check this out.

https://github.com/bachig26/SpotC-Plus-Plus/actions/runs/9669123266/job/26674872185#step:44:46
```
Run softprops/action-gh-release@v2
  
👩‍🏭 Creating new GitHub release for tag v2.1.4...
⚠️ GitHub release failed with status: 403
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release","status":"403"}
Skip retry — your GitHub token/PAT does not have the required permission to create a release
Error: Resource not accessible by integration
```

**Comment by yodaluca23** [comment]
> @yodaluca23 Hi, I tried the new workflow for building ipa with the tweak. can you check this out.
> 
> [bachig26/SpotC-Plus-Plus/actions/runs/9669123266/job/26674872185#step:44:46](https://github.com/bachig26/SpotC-Plus-Plus/actions/runs/9669123266/job/26674872185#step:44:46)
> 
> ```
> Run softprops/action-gh-release@v2
>   
> 👩‍🏭 Creating new GitHub release for tag v2.1.4...
> ⚠️ GitHub release failed with status: 403
> {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release","status":"403"}
> Skip retry — your GitHub token/PAT does not have the required permission to create a release
> Error: Resource not accessible by integration
> ```

I don't really intend for people to use it, it was mostly for me to automate the release of each version... (Unless [Knock on Wood] Spotify were to DMCA me, and not allow me to host them...)

It looks like your GitHub token is not authorized to make a new release on your repo?
Check your workflow permission have read and write:
https://user-images.githubusercontent.com/132504/171749365-d7ec9897-8f3c-4671-9b77-d3af5cb4fe19.png

If so try adding

```permissions:
  contents: write-all```
  to the .yaml
  
  
  https://github.com/softprops/action-gh-release/issues/236
  https://stackoverflow.com/questions/76362343/creating-a-release-using-github-action-fails-with-http-403

**Comment by bachig26** [comment]
> I don't really intend for people to use it, it was mostly for me to automate the release of each version... (Unless [Knock on Wood] Spotify were to DMCA me, and not allow me to host them...)

oh okay. i didn't know that. thanks anyway for providing the solution.
i'll be using your latest release everytime but i may try the latest tweaks or eeveespotify commits that comes in to see at 1st hand before their weekly packaging with your workflow.
