### ISSUE TITLE
SposifyFix [502 Bad Gateway]

### ISSUE THREAD

**Issue by bachig26** [SpotCompiled/SpotC-Plus-Plus#35]
build error code 23: https://github.com/bachig26/SpotC-Plus-Plus/actions/runs/9850961815/job/27197021004#step:20:81

the SposifyFix files/links are gone. @yodaluca23 please have a look.

**Comment by yodaluca23** [comment]
Looks like level3tjg's website is down. I'll try to contact him.

**Comment by yodaluca23** [comment]
It's up again! Try rerunning the workflow.

**Comment by yodaluca23** [comment]
@bachig26 he restarted it and it's working now, it's back up, now rerun the workflow and it should work.

**Comment by bachig26** [comment]
oh. thank you.
