### ISSUE TITLE
couple errors at build - workflow (Run pyzule | Download EeveeSpotify.deb)

### ISSUE THREAD

**Issue by bachig26** [SpotCompiled/SpotC-Plus-Plus#36]
Run pyzule: https://github.com/bachig26/SpotC-Plus-Plus/actions/runs/9851365279/job/27198100054#step:40:39

Download EeveeSpotify.deb: https://github.com/bachig26/SpotC-Plus-Plus/actions/runs/9851342958/job/27198041904#step:24:36

@yodaluca23 i tried few workflow build runs, and i'm getting either of these two errors every time.

**Comment by yodaluca23** [comment]
The second error with downloading the debs is because for some reason sometimes it can't properly fetch the latest release tag. I don't know why I think it may has something to do with the rate limits because if you wait like a couple of minutes and then do it again usually it works the first time

And for the Pyzule error it looks like for some reason Pull bot just completely erased my fork. I have no idea why I'll go fix that now.

**Comment by yodaluca23** [comment]
> And for the Pyzule error it looks like for some reason Pull bot just completely erased my fork. I have no idea why I'll go fix that now.

@bachig26 I was able to recover my commits. Please try it now.

**Comment by bachig26** [comment]
> @bachig26 I was able to recover my commits. Please try it now.

it doesn't show the Pyzule error anymore, but still can't download the latest eeveespotify.deb artifact file.
but works fine with eeveespotify [release package](https://github.com/whoeevee/EeveeSpotify/releases) anyway. i'll try again later today or tomorrow.
thanks.

**Comment by yodaluca23** [comment]
> The second error with downloading the debs is because for some reason sometimes it can't properly fetch the latest release tag. I don't know why I think it may has something to do with the rate limits because if you wait like a couple of minutes and then do it again usually it works the first time

 @bachig26 So I figured out the issue the GitHub public API has strict rate limits, which are very quickly consumed when using the workflow I added an authorization header using the workflow GitHub token which whenever you give authorization, the API rate limits are a lot less strict.
