### ISSUE TITLE
Canvas options in now playing is buggy

### ISSUE THREAD

**Issue by bachig26** [SpotCompiled/SpotC-Plus-Plus#4]
the canvas options seems to buggy, when I toggle it sometimes it doesn’t work or it will show in the now playing but I can switch between the album art and the canvas tab.

note: there seems to conflict if some option is on and if so some doesn’t work. Also some options says toggle to turn on but feels like it gets turn off.

please look into these issues. 🙏✌️

#### Screenshot

![63F58DDF-5FB7-4602-90C8-F35BF27AEC08](https://user-images.githubusercontent.com/96393348/227555720-ebbf96f7-06c9-4f67-af45-8e4e9eaba737.jpeg)

**Comment by yodaluca23** [comment]
Which settings excactly?

**Comment by bachig26** [comment]
> Which settings exactly?

actually, I forgot it's been so long but I think the setting `Canvas Tab`, `Disable Canvas`.

**Comment by yodaluca23** [comment]
Canvas Toggle is native Spotify option in the latest release.
