### ISSUE TITLE
Can't add source to AltStore PAL

### ISSUE THREAD

**Issue by MattNot** [SpotCompiled/SpotC-Plus-Plus#40]
Hi, i'm not able to add the source to altstore pal. The error says:

"One or more apps in source are missing a marketplaceID"

**Comment by yodaluca23** [comment]
Tweaked apps would likely never be notarized by Apple. I don't ever plan to get this notarized by Apple. I would have to spend lots of money to get this notarized by Apple and would highly highly likely, like 99% chance get declined.
