### ISSUE TITLE
SpotC++ is trying to import from firefox

### ISSUE THREAD

**Issue by AquaFrostByte** [SpotCompiled/SpotC-Plus-Plus#43]
I use FireFox as an main browser and every time i start SpotC++ it ask to copy from Firefox. Why?? Is it scraping my browser cookies?

**Comment by yodaluca23** [comment]
For one, that would just be your clipboard, (so it would show up as whatever you copied from last) two, I've noticed this glitch with a lot of sideloaded apps, I believe it's a glitch with Cydia substrate or something...
