### ISSUE TITLE
[Enhancement] Remove Rating Pop-Up

### ISSUE THREAD

**Issue by bachig26** [SpotCompiled/SpotC-Plus-Plus#5]
@yodaluca23 is it possible to stripe away the Spotify app rating popup that appears from time to time?

also is it a app/client side or server side based popup?

**Comment by yodaluca23** [comment]
Yea, I'm working on it... it should be possible...

**Comment by SellAllThisStuff** [comment]
Dude thank you so much for your work, i literally tried dozens of repacks and only your works. If you could remove this popup it will be just perfect. Good luck.

**Comment by bachig26** [comment]
[v1.4: fixed settings issue, implemented popup on data reload, blocked store review](https://github.com/whoeevee/EeveeSpotify/commit/f11e0cbb38114c454259cd2390bb0c14a5937117)

[dont need that](https://github.com/whoeevee/EeveeSpotify/commit/b710b1156b1f0a82a7ef6c30af8d217a68376a88)

removed the commit, due to some crash with store review being edited-out.
