### ISSUE TITLE
App not visible on Carplay and Siri Not able to Play Music.

### ISSUE THREAD

**Issue by adarid** [SpotCompiled/SpotC-Plus-Plus#50]
The Spotify App is not visible on Carplay and when I say "Hey Siri Play Music on Spotify" it says " to do that, you'll have to verify your account on Spotify"

**Comment by yodaluca23** [comment]
Requires TrollStore, nothing I can do about it.

**Comment by cstout1** [comment]
@yodaluca23 I'm curious about the technical reason for this. Is this because of some Trollstore certificates magic? What does CarPlay require that resigned and sideloaded apps don't have?
