### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by Ijaaktheshark** [SpotCompiled/SpotC-Plus-Plus#7]
{
  "name": "SpotC",
  "identifier": "com.yodaluca23.SpotC",
  "sourceURL": "https://raw.githubusercontent.com/SpotCompiled/SpotC-AltStore-Repo/main/AltStore%20Repo.json",
  "apps": [
    {
      "name": "SpotC++",
      "bundleIdentifier": "com.yodaluca23.SpotCPlusPlus",
      "developerName": "Julioverne & Aesthyrica",
      "version": "1.1.3",
      "versionDate": "2023-1-9",
      "size": 48093000,
      "minOSVersion": "13.0",
      "subtitle": "Spotify Ad-Free, and Other QOL Enhancements.",
      "versions": [
                 {
          "version": "1.1.3",
          "date": "2022-1-9",
          "localizedDescription": "- Added Sposify Fix 0.0.6, which should fix it from crashing when opening settings.\n - Fixed Update loop when using SideStore or AltStore.\n\n More Info:\n https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/tag/v1.1.3",
          "downloadURL": "https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/download/v1.1.3/SpotC++.v1.1.3_v8.6.42.ipa",
          "size": 48093000,
          "minOSVersion": "13.0"
        },
                {
          "version": "1.1.2",
          "date": "2022-1-9",
          "localizedDescription": "- Added Sposify Fix 0.0.6, which should fix it from crashing when opening settings.\n\n More Info:\n https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/tag/v1.1.2",
          "downloadURL": "https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/download/v1.1.2/SpotC++.v1.1.2_v8.6.42.ipa",
          "size": 48093000,
          "minOSVersion": "13.0"
        },
                {
          "version": "1.1.1",
          "date": "2022-1-1",
          "localizedDescription": "First AltStore release!\n Crashes when opening Settings, not recommended to use.\n\n More Info:\n https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/tag/v1.1.1",
          "downloadURL": "https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/download/v1.1.1/SpotC++.v1.1.1_v8.6.42.ipa",
          "size": 48068000,
          "minOSVersion": "13.0"
        }
      ],
      "downloadURL": "https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/download/v1.1.3/SpotC++.v1.1.3_v8.6.42.ipa",
      "localizedDescription": "Spotilife is a Spotify IOS app tweak that removes ads, removes limited skips, and almost every other premium feature. The only main premium feature that does not work is offline downloads, as this is done server-side.\n\n Sposify is a Spotify IOS app tweak that adds various enhancements to the Spotify IOS application.\n\n More Info:\n https://github.com/SpotCompiled/SpotC-Plus-Plus\n\n We are not affiliated, associated, authorized, endorsed by, or in any way officially connected with any other company, agency or government agency. All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.",
      "iconURL": "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/SpotC%2B%2B%20AppIcon.png",
      "tintColor": "1ed760",
      "permissions": [
        {
          "type": "camera",
          "usageDescription": "This lets you scan Spotify Codes."
        },
        {
          "type": "photos",
          "usageDescription": "This lets you save and select images to and from your Photo Library."
        },
        {
          "type": "music",
          "usageDescription": "This will let you play your imported music on Spotify."
        },
        {
          "type": "motion",
          "usageDescription": "Used to control your tempo for Spotify Running."
        },
        {
          "type": "microphone",
          "usageDescription": "This lets you control Spotify using your voice."
        },
        {
          "type": "bluetooth",
          "usageDescription": "This lets you use Spotify with external accessories."
        },
        {
          "type": "network",
          "usageDescription": "This lets you listen on different devices. Spotify will also get access to local audio files."
        },
        {
          "type": "faceid",
          "usageDescription": "This lets you set access restrictions using Face ID."
        }
      ],
      "screenshotURLs": [
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Sposify%20Settings%201.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Sposify%20Settings%202.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Sposify%20Car%20Mode.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Spotilife%20Playing%20SS.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Spotilife%20PlayList%20SS.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Spotilife%20Library%20View%20SS.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Sposify%20Lyrics%20Screen.png"
      ],
      "beta": false
    },
    {
      "name": "SpotilifeC",
      "bundleIdentifier": "com.yodaluca23.SpotilifeC",
      "developerName": "Julioverne",
      "version": "1.2.3",
      "versionDate": "2023-1-9",
      "size": 47954000,
      "minOSVersion": "13.0",
      "subtitle": "Spotify No ads Tweak",
      "versions": [
                {
          "version": "1.2.3",
          "date": "2023-1-1",
          "localizedDescription": "- Fixed Update loop when using SideStore or AltStore.\n\n More Info:\n https://github.com/SpotCompiled/SpotilifeC/releases/tag/v1.2.3",
          "downloadURL": "https://github.com/SpotCompiled/SpotilifeC/releases/download/v1.2.3/SpotilifeC.v1.2.3_v8.6.42.ipa",
          "size": 47954000,
          "minOSVersion": "13.0"
        },
                {
          "version": "1.2.2",
          "date": "2023-1-1",
          "localizedDescription": "First Version that actually works! 🥳 (Can Verifiy)\n\n More Info:\n https://github.com/SpotCompiled/SpotilifeC/releases/tag/v1.2.2",
          "downloadURL": "https://github.com/SpotCompiled/SpotilifeC/releases/download/v1.2.2/SpotilifeC.v1.2.2_v8.6.42.ipa",
          "size": 47954000,
          "minOSVersion": "13.0"
        },
        {
          "version": "1.2.1",
          "date": "2022-12-21",
          "localizedDescription": "First Version that actually works! 🥳\n\n More Info:\n https://github.com/SpotCompiled/SpotilifeC/releases/tag/v1.2.1",
          "downloadURL": "https://github.com/SpotCompiled/SpotilifeC/releases/download/v1.1.1/SpotilifeC.v1.1.1_v8.7.78.ipa",
          "size": 52661000,
          "minOSVersion": "13.0"
        },
        {
          "version": "1.1.1",
          "date": "2022-10-27",
          "localizedDescription": "First AltStore release!",
          "downloadURL": "https://github.com/SpotCompiled/SpotilifeC/releases/download/v1.1.1/SpotilifeC.v1.1.1_v8.7.78.ipa",
          "size": 6687500,
          "minOSVersion": "13.0"
        }
      ],
      "downloadURL": "https://github.com/SpotCompiled/SpotilifeC/releases/download/v1.2.3/SpotilifeC.v1.2.3_v8.6.42.ipa",
      "localizedDescription": "Spotilife is a Spotify IOS app tweak that removes ads, removes limited skips, and almost every other premium feature. The only main premium feature that does not work is offline downloads, as this is done server-side.\n\n More Info:\n https://github.com/SpotCompiled/SpotilifeC\n\n We are not affiliated, associated, authorized, endorsed by, or in any way officially connected with any other company, agency or government agency. All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.",
      "iconURL": "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/SpotilifeC%20AppIcon.png",
      "tintColor": "1ed760",
      "permissions": [
        {
          "type": "camera",
          "usageDescription": "This lets you scan Spotify Codes."
        },
        {
          "type": "photos",
          "usageDescription": "This lets you save and select images to and from your Photo Library."
        },
        {
          "type": "music",
          "usageDescription": "This will let you play your imported music on Spotify."
        },
        {
          "type": "motion",
          "usageDescription": "Used to control your tempo for Spotify Running."
        },
        {
          "type": "microphone",
          "usageDescription": "This lets you control Spotify using your voice."
        },
        {
          "type": "bluetooth",
          "usageDescription": "This lets you use Spotify with external accessories."
        },
        {
          "type": "network",
          "usageDescription": "This lets you listen on different devices. Spotify will also get access to local audio files."
        },
        {
          "type": "faceid",
          "usageDescription": "This lets you set access restrictions using Face ID."
        }
      ],
      "screenshotURLs": [
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Spotilife%20Playing%20SS.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Spotilife%20PlayList%20SS.png",
        "https://github.com/SpotCompiled/SpotC-AltStore-Repo/raw/main/Spotilife%20Library%20View%20SS.png"
      ],
      "beta": false
    }
  ]
}

**Comment by yodaluca23** [comment]
Why are you just coping the code from my AltStore repo and making it an issue??
